
import __ASTRO_IMAGE_IMPORT_vYkuj from "../../assets/blog/creating-an-amazing-github-profile/add-repo-description.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md";
import __ASTRO_IMAGE_IMPORT_Z10NAQl from "../../assets/blog/creating-an-amazing-github-profile/awesome-github-profile-tumb.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md";
import __ASTRO_IMAGE_IMPORT_1u60MR from "../../assets/blog/creating-an-amazing-github-profile/create-code.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md";
import __ASTRO_IMAGE_IMPORT_1dQBXb from "../../assets/blog/creating-an-amazing-github-profile/example-profile.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md";
import __ASTRO_IMAGE_IMPORT_1BGTrV from "../../assets/blog/creating-an-amazing-github-profile/fill-info.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md";
import __ASTRO_IMAGE_IMPORT_CPkjN from "../../assets/blog/creating-an-amazing-github-profile/follow.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md";
import __ASTRO_IMAGE_IMPORT_Z15Ssbs from "../../assets/blog/creating-an-amazing-github-profile/github.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md";
import __ASTRO_IMAGE_IMPORT_Zl9GFx from "../../assets/blog/creating-an-amazing-github-profile/open-source.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md";
import __ASTRO_IMAGE_IMPORT_1lD8PL from "../../assets/blog/creating-an-amazing-github-profile/pined-repos.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md";
import __ASTRO_IMAGE_IMPORT_Z1WCvbO from "../../assets/blog/useful-vscode-extensions/vscode-extensions-thumb.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fuseful-vscode-extensions.md";
export default new Map([["../../assets/blog/creating-an-amazing-github-profile/add-repo-description.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md", __ASTRO_IMAGE_IMPORT_vYkuj], ["../../assets/blog/creating-an-amazing-github-profile/awesome-github-profile-tumb.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md", __ASTRO_IMAGE_IMPORT_Z10NAQl], ["../../assets/blog/creating-an-amazing-github-profile/create-code.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md", __ASTRO_IMAGE_IMPORT_1u60MR], ["../../assets/blog/creating-an-amazing-github-profile/example-profile.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md", __ASTRO_IMAGE_IMPORT_1dQBXb], ["../../assets/blog/creating-an-amazing-github-profile/fill-info.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md", __ASTRO_IMAGE_IMPORT_1BGTrV], ["../../assets/blog/creating-an-amazing-github-profile/follow.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md", __ASTRO_IMAGE_IMPORT_CPkjN], ["../../assets/blog/creating-an-amazing-github-profile/github.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md", __ASTRO_IMAGE_IMPORT_Z15Ssbs], ["../../assets/blog/creating-an-amazing-github-profile/open-source.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md", __ASTRO_IMAGE_IMPORT_Zl9GFx], ["../../assets/blog/creating-an-amazing-github-profile/pined-repos.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreating-an-amasing-github-profile.md", __ASTRO_IMAGE_IMPORT_1lD8PL], ["../../assets/blog/useful-vscode-extensions/vscode-extensions-thumb.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fuseful-vscode-extensions.md", __ASTRO_IMAGE_IMPORT_Z1WCvbO]]);
		